---
title: "John McBride"
subtitle: "~1804 - 1860"
knit: (function(inputFile, encoding) { 
      out_dir <- '../John McBride';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'Biography.PDF')) })
output: pdf_document
urlcolor: blue
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

##Immediate Family
* Father: UNKNOWN
* Mother: UNKNOWN
* spouses: 
    1. Olive C Vanarsdall
    2. Mary J Caldwell
* Children:
    1. Matilda W McBride (b. 1832)
    2. William R McBride (b. 1834)
    3. George C McBride (b. 1836)
    4. Samuel H McBride (b. 1840)
    5. [Isaac B McBride](../Isaac V McBride/Biography.PDF) (b. 1842)
    5. Syrena F McBride (b. 1845)
    6. Nancy Bell McBride (b. 1849)
    1. Felix Smith McBride (b. 1852)
    2. John C. McBride (b. 1855)
    3. Mary?? Catherine?? McBride (b. 1858)

##Bio

John McBride was born circa 1804 in Kentucky (Felix's [death certificate](../Felix Smith McBride/Death Record.jpg), [1850 census](Censuses/1850 Census.jpg), all but one of [Isaac](../Isaac V McBride/BIO.PDF)'s censuses). Felix's death certificate claims he was born in Boyle County, but the county wasn't founded until [1842](http://boyleky.com) (external link). It is possible he was born in Mercer County, parts of which became Boyle county. In 1831 John [married](Marriage Liscense.jpg) Olive C Vanarsdall in Mercer County. He was 27 and she was between [11](Censuses/1840 Census.jpg) and [19](../Isaac Brooks Vanarsdall/Marriage Liscense.jpg) (although I would assume the older end of that range). By [1840](Censuses/1840 Census.jpg) They were living in Mercer County, Kentucky, with two sons under five, one son between five and ten, one daughter under five, and one daughter between five and ten. Between 1849 and 1850 John's wife Olive had passed away ([1850 census](Censuses/1850 Census.jpg)). John was living with all seven living children he had from his marriage. One of his children must have died or married very young because he had a daughter under five on the 1840 census who does not appear on the 1850 census. Between [1850](Censuses/1850 Census.jpg) and [1852](Censuses/1860 Census.jpg) John married Mary J Caldwell, who was 18 years his junior. By [1860](Censuses/1860 Census.jpg) John had had three children with Mary and they were living together in Boone County, Missouri. John died in 1860. In his [will](Will.jpg), in which his brother in law and oldest son, William, were executors, he asks for real and personaly property and land to be sold "for the best and highest price". He then wants one thousand dollars to go to his wife, along with a set of silver tea spoons and enough money to get her and her children to Marion County, Kentucky. He leaves his daughter Matilda one hundred and fifty dollars, his daughter Nancy one third of his estate, and his children William, George, Syrena Felix, John C, and Mary the rest of his estate. He leaves his sons Samuel and Isaac one dollar each. This leads me to believe they had some kind of falling out near the end of John's life.